### PR TITLE
pkg: replace `utils/strings/InSlice` func with `slices.Contains`

### LINKED ISSUE #245: replace `utils/strings/InSlice` to `slices.Contains`
Now we don't need this deprecated function `InSlice`:

https://github.com/aquasecurity/trivy-db/blob/main/pkg/utils/strings/strings.go#L28-L35

### PR DESCRIPTION
**Pull request by mohamedawnallah**
## Description

In this commit, we replace `utils/strings/InSlice` function with the built-in `slices.Contains` function which is supported in go 1.18+ and it would work with the current project go version `1.19` as appears in the `go.mod` file.

Closes #245

## How has this been tested?

I've run the test cases using `make test` and all of them passed.

### CODE REVIEW

**Review by knqyf263 — APPROVED** [review]

**Comment by knqyf263** [comment]
I think `slices` was added to the standard package in Go 1.21.

**Comment by mohamedawnallah** [comment]
Ah sorry my bad. Your are right:
https://pkg.go.dev/slices?tab=versions

**Comment by knqyf263** [comment]
opened https://github.com/aquasecurity/trivy-db/pull/415

**Comment by knqyf263** [comment]
Thanks

**Pull request merged**
