### PR TITLE
upgrade to Go 1.15

### PR DESCRIPTION
**Pull request by neha-viswanathan**
This MR updates the base image to Go 1.15

### CODE REVIEW

**Review by knqyf263 — CHANGES_REQUESTED** [review]
You have to fix a few more things. The following PR should be helpful.
https://github.com/aquasecurity/trivy/pull/646

Also, did you apply `go mod tidy`? If so, never mind.

**Comment by neha-viswanathan** [comment]
@knqyf263 thanks! yes I did run `go mod tidy`

**Review by knqyf263 — CHANGES_REQUESTED** [review]
Could you update Go runtime version in go.mod?

**Review by knqyf263 — APPROVED** [review]

**Comment by knqyf263** [comment]
Thanks! If you need `#hacktoberfest-accepted` label, let me know, please.

**Comment by neha-viswanathan** [comment]
Sure that'd be great. Thanks @knqyf263

**Comment by knqyf263** [comment]
done

**Pull request merged**
