### PR TITLE
feat: add support for Ubuntu 24.10 "Oracular Oriole"

### PR DESCRIPTION
**Pull request by itsdean**
I noticed trivy did not currently output any vulnerability information for Ubuntu 24.10, so this adds support for it.

### CODE REVIEW

**Review by DmitriyLewen — APPROVED** [review]
Hello @itsdean 
Thanks for your work!

I confirm that it works: 
изображение
cc. @knqyf263 

@itsdean do you have time to open PR in `trivy` (example for 24.04 - https://github.com/aquasecurity/trivy/pull/6573)

**Comment by itsdean** [comment]
@DmitriyLewen I can open a PR to add the EoL date in `trivy`!

**Comment by DmitriyLewen** [comment]
@itsdean Great! thanks!

**Comment by itsdean** [comment]
Raised via https://github.com/aquasecurity/trivy/pull/7787 - please take a look when you can.

**Review by knqyf263 — APPROVED** [review]

**Comment by knqyf263** [comment]
Thanks

**Pull request merged**
