### PR TITLE
feat: fetch k8s cves from kubernetes-sigs/cve-feed-osv

### PR DESCRIPTION
**Pull request by chen-keinan**
## Description

The purpose of this change is to collect kubernetes cves data from kubernetes-sigs/cve-feed-osv which is  relable and has osv format, instead of the existing k8s collector

- Related https://github.com/kubernetes-sigs/cve-feed-osv/issues/1

### CODE REVIEW

**Review by DmitriyLewen — COMMENTED** [review]
I thought about `vuln-list-k8s` repository.
After merging this PR, we may want to delete/stop updating this repository.
@chen-keinan @knqyf263 wdyt?

**Comment by knqyf263** [comment]
Yes, we should stop vuln-list-k8s and archive it.

**Review by knqyf263 — APPROVED** [review]
LGTM

**Review by DmitriyLewen — APPROVED** [review]
LGTM

**Pull request merged**
