### PR TITLE
added openSUSE Tumbleweed version detection

### PR DESCRIPTION
**Pull request by msmeissn**
(Tumbleweed has no version as it is rolling)

https://github.com/aquasecurity/trivy-db/issues/410

### CODE REVIEW

**Review by DmitriyLewen — COMMENTED** [review]
Hello @msmeissn 
Thanks for your work!

LGTM, but add [test](https://github.com/aquasecurity/trivy-db/blob/79d0fbd1e246f3c77eef4b9826fe4bf65940b221/pkg/vulnsrc/suse-cvrf/suse-cvrf_test.go) for  `openSUSE Tumbleweed` please.


UPD:
Fix linter errors, please.

**Comment by msmeissn** [comment]
will do

**Comment by msmeissn** [comment]
I got it make lint clean.

I added a openSUSE Tumbleweed testcase, "make check" works (only FAILS in the GHSA parts).

**Review by DmitriyLewen — APPROVED** [review]
LGTM

@knqyf263 take a look, when you have time, please

**Comment by knqyf263** [comment]
@DmitriyLewen Did you build trivy-db and it looked fine?

**Comment by DmitriyLewen** [comment]
Yes. Looks good.
`openSUSE Tumbleweed` contains a lot of buckets, but I've now rechecked and it looks as expected.
Screenshot from 2024-06-26 10-02-14

**Comment by knqyf263** [comment]
Oh, 17,376 buckets. How about the database size?

**Comment by DmitriyLewen** [comment]
+ `0.6 MB` before unzip
+ `16 MB` after unzip


```bash
➜  ls -l ./assets    
total 517492
-rw-rw-r-- 1 dmitriy dmitriy  51106757 июн 26 12:34 db.tar.gz
-rw-rw-r-- 1 dmitriy dmitriy       143 июн 26 12:34 metadata.json
-rw------- 1 dmitriy dmitriy 480534528 июн 26 12:34 trivy.db
➜  ls -l ./assets-new
total 536156
-rw-rw-r-- 1 dmitriy dmitriy  51696853 июн 26 12:13 db.tar.gz
-rw-rw-r-- 1 dmitriy dmitriy       143 июн 26 09:59 metadata.json
-rw------- 1 dmitriy dmitriy 497311744 июн 26 09:59 trivy.db

```

**Comment by knqyf263** [comment]
> * `0.6 MB` before unzip
> * `16 MB` after unzip
> 
> ```shell
> ➜  ls -l ./assets    
> total 517492
> -rw-rw-r-- 1 dmitriy dmitriy  51106757 июн 26 12:34 db.tar.gz
> -rw-rw-r-- 1 dmitriy dmitriy       143 июн 26 12:34 metadata.json
> -rw------- 1 dmitriy dmitriy 480534528 июн 26 12:34 trivy.db
> ➜  ls -l ./assets-new
> total 536156
> -rw-rw-r-- 1 dmitriy dmitriy  51696853 июн 26 12:13 db.tar.gz
> -rw-rw-r-- 1 dmitriy dmitriy       143 июн 26 09:59 metadata.json
> -rw------- 1 dmitriy dmitriy 497311744 июн 26 09:59 trivy.db
> ```

Looks reasonable.

**Pull request merged**
