### PR TITLE
pkg: Sunset VendorVectors 🌅

### PR DESCRIPTION
**Pull request by simar7**
`VendorVectors` has been deprecated for a while now.
We have decided to sunset the support for it with this commit.

Users are encouraged to use `CVSS` instead which
includes all the information (and more) that `VendorVectors` had.

Signed-off-by: Simarpreet Singh <simar@linux.com>

### CODE REVIEW

**Comment by knqyf263** [comment]
It looks good. We have to announce this deprecation before merging this PR in GitHub Discussions and README. I won't approve this PR until then, just in case.

**Comment by simar7** [comment]
> It looks good. We have to announce this deprecation before merging this PR in GitHub Discussions and README. I won't approve this PR until then, just in case.
> https://github.com/aquasecurity/trivy/discussions

OK I started the discussion here https://github.com/aquasecurity/trivy/discussions/651

**Comment by knqyf263** [comment]
@simar7 Thanks!

**Comment by simar7** [comment]
14 days since the said announcement have passed, @knqyf263 could you review this again and approve so we can merge it?

**Review by knqyf263 — APPROVED** [review]

**Pull request merged**
